export const data = [
    {
        id: '1',
        new: false,
        date: '01.02.2023',
        priority: 'normal',
        equipment: 'Вегас1',
        message: 'Сервер недоступен Сервер недоступен ',
        responsible: 'Иванов1 И.',
    },
    {
        id: '2',
        new: true,
        date: '01.03.2023',
        priority: 'normal',
        equipment: 'Вега2',
        message: 'Сервер недоступен',
        responsible: 'Иванов2 И.',
    },
    {
        id: '3',
        new: true,
        date: '01.04.2023',
        priority: 'normal',
        equipment: 'Вегас3',
        message: 'Сервер недоступен',
        responsible: 'Иванов3 И.',
    },
    {
        id: '4',
        new: true,
        date: '01.05.2023',
        priority: 'normal',
        equipment: 'Вегас4',
        message: 'Сервер недоступен',
        responsible: 'Иванов4 И.',
    },
    {
        id: '5',
        new: true,
        date: '01.06.2023',
        priority: 'normal',
        equipment: 'Вегас5',
        message: 'Сервер недоступен',
        responsible: 'Иванов5 И.',
    },
];
