export const data = [
    {
        id: 1,
        date: '01.02.2023',
        priority: 'normal',
        equipment: 'Вегас1',
        message: 'Сервер недоступен Сервер недоступен ',
        responsible: 'Иванов1 И.',
    },
    {
        id: 2,
        date: '01.03.2023',
        priority: 'normal',
        equipment: 'Вега2',
        message: 'Сервер недоступен',
        responsible: 'Иванов2 И.',
    },
    {
        id: 3,
        date: '01.04.2023',
        priority: 'normal',
        equipment: 'Вегас3',
        message: 'Сервер недоступен',
        responsible: 'Иванов3 И.',
    },
    {
        id: 4,
        date: '01.05.2023',
        priority: 'normal',
        equipment: 'Вегас4',
        message: 'Сервер недоступен',
        responsible: 'Иванов4 И.',
    },
    {
        id: 5,
        date: '01.06.2023',
        priority: 'normal',
        equipment: 'Вегас5',
        message: 'Сервер недоступен',
        responsible: 'Иванов5 И.',
    },
    {
        id: 11,
        date: '01.07.2023',
        priority: 'normal',
        equipment: 'Вегас1',
        message: 'Сервер недоступен',
        responsible: 'Иванов1 И.',
    },
    {
        id: 12,
        date: '21.02.2023',
        priority: 'normal',
        equipment: 'Вега2',
        message: 'Сервер недоступен',
        responsible: 'Иванов2 И.',
    },
    {
        id: 13,
        date: '22.02.2023',
        priority: 'normal',
        equipment: 'Вегас3',
        message: 'Сервер недоступен',
        responsible: 'Иванов3 И.',
    },
    {
        id: 14,
        date: '11.02.2023',
        priority: 'normal',
        equipment: 'Вегас4',
        message: 'Сервер недоступен',
        responsible: 'Иванов4 И.',
    },
    {
        id: 15,
        date: '01.12.2023',
        priority: 'normal',
        equipment: 'Вегас5',
        message: 'Сервер недоступен',
        responsible: 'Иванов5 И.',
    },
];
